name: 'Ig post'
on:
  schedule:
    - cron: "00 11,18 * * *"
  workflow_dispatch:

jobs:
  ig-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: |
          git pull origin master

      - run: |
          npm install
          npm rebuild canvas --update-binary

      - name: Post to Instagram
        uses: ./instagram autoposter
        id: insta
        with:
          password: ${{ secrets.IG_PASSWORD }}
          unsplashApiKey: ${{ secrets.UNSPLASH_API_KEY }}

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "New instagram post !" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true