name: 'Ig post'
on:
  schedule:
    - cron: "00 11,18 * * *"
  workflow_dispatch:

jobs:
  ig-post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'

      - run: |
          git pull origin master

      - run: |
          npm install
          npm rebuild canvas --update-binary

      - name: Post to Instagram
        uses: ./instagram autoposter
        id: insta
        with:
          password: ${{ secrets.IG_PASSWORD }}
          unsplashApiKey: ${{ secrets.UNSPLASH_API_KEY }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true